// Code generated by Kitex v0.7.2. DO NOT EDIT.

package userservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	user "github.com/li1553770945/sheepim-user-service/kitex_gen/user"
)

func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

var userServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{
		"CheckUsernameAndPasswd": kitex.NewMethodInfo(checkUsernameAndPasswdHandler, newUserServiceCheckUsernameAndPasswdArgs, newUserServiceCheckUsernameAndPasswdResult, false),
		"AddUser":                kitex.NewMethodInfo(addUserHandler, newUserServiceAddUserArgs, newUserServiceAddUserResult, false),
		"GetUserInfo":            kitex.NewMethodInfo(getUserInfoHandler, newUserServiceGetUserInfoArgs, newUserServiceGetUserInfoResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":     "user",
		"ServiceFilePath": `idl/user.thrift`,
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.7.2",
		Extra:           extra,
	}
	return svcInfo
}

func checkUsernameAndPasswdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceCheckUsernameAndPasswdArgs)
	realResult := result.(*user.UserServiceCheckUsernameAndPasswdResult)
	success, err := handler.(user.UserService).CheckUsernameAndPasswd(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceCheckUsernameAndPasswdArgs() interface{} {
	return user.NewUserServiceCheckUsernameAndPasswdArgs()
}

func newUserServiceCheckUsernameAndPasswdResult() interface{} {
	return user.NewUserServiceCheckUsernameAndPasswdResult()
}

func addUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceAddUserArgs)
	realResult := result.(*user.UserServiceAddUserResult)
	success, err := handler.(user.UserService).AddUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceAddUserArgs() interface{} {
	return user.NewUserServiceAddUserArgs()
}

func newUserServiceAddUserResult() interface{} {
	return user.NewUserServiceAddUserResult()
}

func getUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetUserInfoArgs)
	realResult := result.(*user.UserServiceGetUserInfoResult)
	success, err := handler.(user.UserService).GetUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetUserInfoArgs() interface{} {
	return user.NewUserServiceGetUserInfoArgs()
}

func newUserServiceGetUserInfoResult() interface{} {
	return user.NewUserServiceGetUserInfoResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CheckUsernameAndPasswd(ctx context.Context, req *user.CheckUsernameAndPasswdReq) (r *user.CheckUsernameAndPasswdResp, err error) {
	var _args user.UserServiceCheckUsernameAndPasswdArgs
	_args.Req = req
	var _result user.UserServiceCheckUsernameAndPasswdResult
	if err = p.c.Call(ctx, "CheckUsernameAndPasswd", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddUser(ctx context.Context, req *user.AddUserReq) (r *user.AddUserResp, err error) {
	var _args user.UserServiceAddUserArgs
	_args.Req = req
	var _result user.UserServiceAddUserResult
	if err = p.c.Call(ctx, "AddUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserInfo(ctx context.Context, req *user.UserInfoReq) (r *user.UserInfoResp, err error) {
	var _args user.UserServiceGetUserInfoArgs
	_args.Req = req
	var _result user.UserServiceGetUserInfoResult
	if err = p.c.Call(ctx, "GetUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
