// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"sheepim-user-service/biz/infra/config"
	"sheepim-user-service/biz/infra/database"
	"sheepim-user-service/biz/internal/repo"
	"sheepim-user-service/biz/internal/service"
)

// Injectors from wire.go:

func GetContainer(path string) *Container {
	configConfig := config.InitConfig(path)
	db := database.NewDatabase(configConfig)
	iRepository := repo.NewRepository(db)
	iUserService := user.NewUserService(iRepository)
	container := NewContainer(configConfig, iUserService)
	return container
}
