// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/li1553770945/sheepim-user-service/biz/infra/config"
	"github.com/li1553770945/sheepim-user-service/biz/infra/database"
	"github.com/li1553770945/sheepim-user-service/biz/internal/repo"
	"github.com/li1553770945/sheepim-user-service/biz/internal/service"
)

// Injectors from wire.go:

func GetContainer(cfg *config.Config) *Container {
	db := database.NewDatabase(cfg)
	iRepository := repo.NewRepository(db)
	iUserService := user.NewUserService(iRepository)
	container := NewContainer(cfg, iUserService)
	return container
}
